# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BrainCoTech/FlutteriOSSpecs.git'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SnapKit'

 #flutter
#  pod 'FlutteriOSPod', :path => '../FlutteriOSPod'
#   pod 'FlutteriOSPod', :git=> 'git@github.com:BrainCoTech/FlutteriOSPod.git', :tag => '0.0.1'
   pod 'FlutteriOSPod', '~>0.0.1'

end
